# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bM5TMXde9iPtRebaIe0OjSDJ4mN7mv2_
"""

#importing pandas and datasets
import pandas as pd

df_dep=pd.read_csv('departments.csv')

df_emp=pd.read_csv('employees.csv')

#Fetch all rows and columns from the employees table.

df_emp

#Find employees whose age is greater than 30.

df_emp[df_emp['age']>30]

#Retrieve the name and salary columns from the employees table.

df_emp[['name','salary']]

#Find the total salary paid to employees grouped by their department.

p=df_emp.groupby('department_id')['salary'].sum().reset_index()
p.rename(columns={'salary':'total_salary'},inplace=True)
p

#List all employees ordered by their salary in descending order.

s=df_emp.sort_values('salary',ascending=False)
s

#Combine employees and departments tables to include department names.

j=pd.merge(df_emp,df_dep,on='department_id')
j

#Find the rank of employees based on their salary within each department.

df_emp['rank']=j.groupby('department_name')['salary'].rank(method='dense', ascending=False)
df_emp

#Find employees whose salary is above the average salary in the company.

avg_sal=df_emp['salary'].mean()
new=df_emp[df_emp['salary']>avg_sal]
new

#Find departments with an average salary greater than 50,000.

df_avg_salary = df_emp.groupby('department_id')['salary'].mean().reset_index() # Replace df with df_emp
df_high_salary_depts = df_avg_salary[df_avg_salary['salary'] > 50000]
df_high_salary_depts