# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bM5TMXde9iPtRebaIe0OjSDJ4mN7mv2_
"""

import pandas as pd

df_dep=pd.read_csv('departments.csv')

df_emp=pd.read_csv('employees.csv')

df_emp

df_dep

df_emp[df_emp['age']>30]

df_emp[['name','salary']]

p=df_emp.groupby('department_id')['salary'].sum().reset_index()
p.rename(columns={'salary':'total_salary'},inplace=True)
p

s=df_emp.sort_values('salary',ascending=False)
s

j=pd.merge(df_emp,df_dep,on='department_id')
j

df_emp['rank']=j.groupby('department_name')['salary'].rank(method='dense', ascending=False)
df_emp

avg_sal=df_emp['salary'].mean()
new=df_emp[df_emp['salary']>avg_sal]
new